#include <std.h>

BYTE *tx[] = {
  "\0",
  " Yes ",
  " No  ",
  " Ok ",
  "  Error on file open %s !  ",
  "  Existing record !  ",
  "  Illegal input !  ",
  "  Buffer error !  ",
  " Printing ...  ",
  " Processing ...  ",
  " Finished  ",
  " Filename  ",
  "  Updated !  ",
  "  NOT Updated !  ",
  " File ",
  " Search ",
  " Edit ",
  " Help ",
  " eXit ",
  " Insert ",
  " Delete ",
  " Update ",
  " First            ",
  " Next             ",
  " Previous         ",
  " Last             ",
  " Equals           ",
  " Greater than     ",
  " gReater or equal ",
  " Less than        ",
  " less Or equal    ",
  " select Index     ",
  " Match pattern    ",
  " Upshift      ",
  " Downshift    ",
  " Clear_line   ",
  " clear_to_Eol ",
  " Options     ",
  " Help screen ",
  " Quit  ",
  " neW   ",
  " Next  ",
  " Prev  ",
  " Opt   ",
  " Del   ",
  " Ceol  ",
  " cLn   ",
  " Upper ",
  " Lower ",
  " End   ",
  " Top   ",
  " Waiting on lock ",
  " Load  ",
  " Save  ",
  " Go    ",
  " seleCt",
  " Device",
  " Page length",
  " Page width ",
  " Page ",
  " Pages",
  " Lines",
  " Colors ",
  " Text ",
  " SYSTEM TEXT ",
  " View ",
  " New entry",
  " Old entry",
  "Cancel",
  "Maintenance ",
  "Report  ",
  "  Select",
  " Date on the format %s ",
  " "
  };

short tx_dim = sizeof( tx) / sizeof( tx[0]);
