#include <stdio.h>
#include <std.h>
#include <str.h>

struct felt {
  BYTE lname[30];
  BYTE uname[30];
  BYTE len[30];
  };

int main( int ac, char *av[])
  {
  short i,n,maxlen;
  BYTE str[BUFSIZ], field[30], len[30], modul[30], mod_l[30], filename[30];
  struct felt f[50];
  BOOL goon;
  FILE *fh;
  if (ac!=2)
    return (FAIL);
  strcpy( modul, av[1]);
  strcpy( mod_l, av[1]);
  STR_upshift( modul);
  STR_downshift( mod_l);
  for  (i=maxlen=0, goon = TRUE; goon && i<50; i++)
    {
    if (scanf( "%s %s", field, len) == EOF)
      goon = FALSE;
    else
      {
      if (maxlen < strlen( field) )
        maxlen = strlen( field);
      strcpy( f[i].len, len);
      STR_upshift( field);
      strcpy( f[i].uname, field);
      STR_downshift( field);
      strcpy( f[i].lname, field);
      }
    }
  n = i - 1;
  strcpy( filename, mod_l);
  strcat( filename, ".h");
  if ( (fh = fopen( filename, "w") ) == NULL)
    return(FAIL);
  fprintf(fh,"#ifndef %s_H\n",modul);
  fprintf(fh,"#define %s_H\n",modul);
  fprintf(fh,"\n");
  fprintf(fh,"#include <vc.h>\n");
  fprintf(fh,"\n");
  fprintf(fh,"/** MACROS **/\n");
  fprintf(fh,"\n");
  fprintf(fh,"#define %s_TX_FILE \"%s.TXR\"\n",modul,modul);
  fprintf(fh,"\n");
  for (i=0; i<n; i++)
    fprintf(fh,"#define %s_LEN_%s %s\n",modul,f[i].uname,f[i].len);
  fprintf(fh,"\n");
  fprintf(fh,"#define %s_MAX_FID (UI_FID+ %s_max_field - 1)\n",modul,modul);
  fprintf(fh,"#define %s_CLUSTER 50\n",modul);
  fprintf(fh,"\n");
  fprintf(fh,"/** TYPES **/\n");
  fprintf(fh,"\n");
  fprintf(fh,"enum %s_e { ",mod_l);
  for (i=0; i<n; i++)
    fprintf(fh,"%s_%s,",modul,f[i].lname);
  fprintf(fh,"%s_max_field };\n",modul);
  fprintf(fh,"\n");
  fprintf(fh,"struct %s {\n",mod_l);
  for (i=0; i<n; i++)
    fprintf(fh,"  BYTE %s[%s_LEN_%s + 1];\n",f[i].lname,modul,f[i].uname);
  fprintf(fh,"  CISAM cisam;\n");
  fprintf(fh,"  BYTE *fp[%s_max_field];\n",modul);
  fprintf(fh,"  short len[%s_max_field];\n",modul);
  fprintf(fh,"  };\n");
  fprintf(fh,"typedef struct %s %s;\n",mod_l,modul);
  fprintf(fh,"\n");
  fprintf(fh,"extern BYTE *%s_tx[];\n",modul);
  fprintf(fh,"\n");
  fprintf(fh,"/** PROTOTYPES **/\n");
  fprintf(fh,"BOOL %s_begin( %s *%s);\n",modul,modul, mod_l);
  fprintf(fh,"  /*\n");
  fprintf(fh,"  Opens for use of this module, opens files ...\n");
  fprintf(fh,"  */\n");
  fprintf(fh,"void %s_end( %s *%s);\n",modul,modul, mod_l);
  fprintf(fh,"  /*\n");
  fprintf(fh,"  Closes this module for use, closes files ...\n");
  fprintf(fh,"  */\n");
  fprintf(fh,"BOOL %s_ctrl( %s *%s, UI *ui, short id, BYTE *oldfield);\n",modul,modul, mod_l);
  fprintf(fh,"BOOL %s_put( %s *%s, short fn);\n",modul,modul, mod_l);
  fprintf(fh,"BOOL %s_fetch( %s *%s);\n",modul,modul,mod_l);
  fprintf(fh,"BOOL %s_get( %s *%s, short fn);\n",modul,modul, mod_l);
  fprintf(fh,"void %s_options( %s *%s, short id);\n",modul,modul, mod_l);
  fprintf(fh,"BOOL %s_maint( %s *%s);\n",modul,modul, mod_l);
  fprintf(fh,"BOOL %s_popup( %s *%s);\n",modul,modul, mod_l);
  fprintf(fh,"BOOL %s_report( %s *%s);\n",modul,modul, mod_l);
  fprintf(fh,"\n");
  fprintf(fh,"#endif\n");
  fclose(fh);
  strcpy( filename, mod_l);
  strcat( filename, ".c");
  if ( (fh = fopen( filename, "w") ) == NULL)
    return(FAIL);
  fprintf(fh,"#include \"%s.h\"\n",mod_l);
  fprintf(fh,"\n");
  fprintf(fh,"BYTE *%s_tx[] = {\n",modul);
  for (i=0; i<n; i++)
    fprintf(fh,"  \"%s\",\n",f[i].lname);
  fprintf(fh,"  \"  %s  \"\n",modul);
  fprintf(fh,"  };\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_begin( %s *%s)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  short len, dim, i, j;\n");
  fprintf(fh,"  BOOL status;\n");
  fprintf(fh,"  dim = sizeof( %s_tx) / sizeof( %s_tx[0]);\n",modul,modul);
  fprintf(fh,"  VC_tx_load( %s_tx, VC_DIM( %s_tx), %s_TX_FILE);\n",modul,modul,modul);
  for (i=0; i<n; i++)
    fprintf(fh,"  %s->fp[%d] = %s->%s;   %s->len[%d] = %s_LEN_%s;\n",
      mod_l, i, mod_l, f[i].lname, mod_l, i, modul, f[i].uname);
  fprintf(fh,"  CISAM_begin( &(%s->cisam), \"%s\");\n",mod_l,modul);
  fprintf(fh,"  for (i=j=0, status=TRUE; i<%s_max_field; i++)\n",modul);
  fprintf(fh,"    {\n");
  fprintf(fh,"    short fieldtype, keytype, ofs, id;\n");
  fprintf(fh,"    keytype = CISAM_KEYTYPE_NOKEY;\n");
  fprintf(fh,"    fieldtype = CISAM_FIELDTYPE_C;\n");
  fprintf(fh,"    ofs = j; id = i;\n");
  fprintf(fh,"    switch (i)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      default :  break;\n");
  fprintf(fh,"      case  %s_%s:\n",modul,f[0].lname);
  fprintf(fh,"        keytype = CISAM_KEYTYPE_UNIQUE;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"    status &= CISAM_field_new( &(%s->cisam), id,\n",mod_l);
  fprintf(fh,"        %s_tx[i], fieldtype, keytype, ofs, %s->len[i]);\n",modul,mod_l);
  fprintf(fh,"    j += %s->len[i];\n",mod_l);
  fprintf(fh,"    }\n");
  fprintf(fh,"  if (status == OK)\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    if ( (status = CISAM_open( &(%s->cisam) ) ) == FAIL)\n",mod_l);
  fprintf(fh,"      MSG_msg( CISAM_error( &(%s->cisam) ) );\n",mod_l);
  fprintf(fh,"    }\n");
  fprintf(fh,"  return (status);\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"void %s_end( %s *%s)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  CISAM_close( &(%s->cisam) );\n",mod_l);
  fprintf(fh,"  CISAM_end( &(%s->cisam) );\n",mod_l);
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_ctrl( %s *%s, UI *ui, short id, BYTE *oldfield)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  short status;\n");
  fprintf(fh,"  BYTE *sp;\n");
  fprintf(fh,"  status = OK;\n");
  fprintf(fh,"  if (VC_FIELD_IS_ALTERED( %s, id, oldfield) )\n",mod_l);
  fprintf(fh,"    {\n");
  fprintf(fh,"    switch (fid)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      default : status = OK; break;\n");
  fprintf(fh,"      case  %s_%s:\n",modul,f[0].lname);
  fprintf(fh,"        VC_IS_UNIQUE( %s, %s_%s, %s->%s);\n",mod_l,modul,f[0].lname,mod_l,f[0].lname);
  fprintf(fh,"        break;\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"    if (status == FAIL)\n");
  fprintf(fh,"      MSG_warn( tx[tx_field_err] );\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  return (status);\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_fetch( %s *%s)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  if ( !CISAM_field_put( &(%s->cisam), %s_%s, %s->%s) )\n",mod_l,modul,f[0].lname,mod_l,f[0].lname);
  fprintf(fh,"    return (FAIL);\n");
  fprintf(fh,"  if ( !CISAM_eq( &(%s->cisam), %s_%s, %s->%s) )\n",mod_l,modul,f[0].lname,mod_l,f[0].lname);
  fprintf(fh,"    return (FAIL);\n");
  fprintf(fh,"  return (VC_get_fields( %s->fp, &(%s->cisam), %s_max_field) );\n",mod_l,mod_l,modul);
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_get( %s *%s, short fn)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  if ( !VC_file_get( &(%s->cisam), fn) )\n",mod_l);
  fprintf(fh,"    {\n");
  fprintf(fh,"    if ( !CISAM_is_eof() )\n");
  fprintf(fh,"      MSG_msg( CISAM_error( &(%s->cisam) ) );\n",mod_l);
  fprintf(fh,"    return (FAIL);\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  if (fn == UI_CMD_SET_IDX)\n");
  fprintf(fh,"    return (OK);\n");
  fprintf(fh,"  return (VC_get_fields( %s->fp, &(%s->cisam), %s_max_field) );\n",mod_l,mod_l,modul);
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_put( %s *%s, short fn)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  BOOL status;\n");
  fprintf(fh,"  if ( (status = VC_put_fields( %s->fp, &(%s->cisam), %s_max_field) ) == FAIL)\n",mod_l,mod_l,modul);
  fprintf(fh,"    MSG_msg( tx[tx_buffer_err]);\n");
  fprintf(fh,"  else\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    CISAM_transaction_begin( &(%s->cisam) );\n",mod_l);
  fprintf(fh,"    while ( !CISAM_lock( &(%s->cisam) ) )\n",mod_l);
  fprintf(fh,"      if (MSG_question( tx[tx_waiting_on_lock]) )\n");
  fprintf(fh,"        return (FAIL);\n");
  fprintf(fh,"    switch (fn)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      case  UI_CMD_INSERT:  status = CISAM_insert(  &(%s->cisam) );  break;\n",mod_l);
  fprintf(fh,"      case  UI_CMD_UPDATE:  status = CISAM_update(  &(%s->cisam) );  break;\n",mod_l);
  fprintf(fh,"      case  UI_CMD_DELETE:  status = CISAM_delete(  &(%s->cisam) );  break;\n",mod_l);
  fprintf(fh,"      default : return (OK);\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"    if (status == FAIL)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      MSG_msg( CISAM_error( &(%s->cisam) ) );\n",mod_l);
  fprintf(fh,"      CISAM_transaction_rollback( &(%s->cisam) );\n",mod_l);
  fprintf(fh,"      }\n");
  fprintf(fh,"    else\n");
  fprintf(fh,"      CISAM_transaction_commit( &(%s->cisam) );\n",mod_l);
  fprintf(fh,"    }\n");
  fprintf(fh,"  return (status);\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"void %s_options( %s *%s, short id)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  switch (id)\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    default : break;\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_maint( %s *%s)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  UI ui;\n");
  fprintf(fh,"  BYTE oldfield[BUFSIZ], s[BUFSIZ];\n");
  fprintf(fh,"  short cmd, fid, occ, oldfid, oldocc, i, j;\n");
  fprintf(fh,"  BOOL goon;\n");
  fprintf(fh,"  sprintf( s, \"%s\", %s_tx[%s_max_field], tx[tx_maint]);\n","%s  -  %s",modul,modul);
  fprintf(fh,"  if ( !UI_begin( &ui, s, W_CENTER, W_CENTER, %d, 40, UI_BUTTON_LEN, color_entry) ) return (FAIL);\n", n);
  fprintf(fh,"  if ( !VC_default_mnubar_maint( &ui) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_button_maint( &ui) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_acksel_maint( &ui) ) return (FAIL);\n");
  fprintf(fh,"  i = j = 0;\n");
  for (i=0; i<n; i++)
    fprintf(fh,"  if ( !UI_ITEM_FIELD( &ui, %s_%s, %s->%s, %s_LEN_%s, i++, %d, %s_tx[%s_%s],   j++, 0) ) return (FAIL);\n"
              ,modul,f[i].lname,mod_l,f[i].lname,modul,f[i].uname,(maxlen+2),modul,modul,f[i].lname);
  fprintf(fh,"  UI_init_items( &ui);\n");
  fprintf(fh,"  UI_paint( &ui);\n");
  fprintf(fh,"  fid = UI_FID; ui.new = TRUE;\n");
  fprintf(fh,"  strcpy( oldfield, UI_item_search( &ui, fid, occ) );\n");
  fprintf(fh,"  for (goon = TRUE, occ = 0; goon; )\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    oldfid = fid;  oldocc = occ;\n");
  fprintf(fh,"    cmd = UI_cmd_get( &ui, &fid, &occ);\n");
  fprintf(fh,"    if (ui.new)\n");
  fprintf(fh,"      UI_status_printf( &ui, tx[tx_new_entry]);\n");
  fprintf(fh,"    else\n");
  fprintf(fh,"      UI_status_printf( &ui, tx[tx_old_entry]);\n");
  fprintf(fh,"    switch (cmd)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      case  UI_CMD_PAINT:\n");
  fprintf(fh,"        UI_paint_client( &ui);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_QUIT:\n");
  fprintf(fh,"        goon = FALSE;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_NEW:\n");
  fprintf(fh,"        UI_init_items( &ui);\n");
  fprintf(fh,"        fid = UI_FID;\n");
  fprintf(fh,"        CISAM_setidx( &(%s->cisam), fid);\n",mod_l);
  fprintf(fh,"        ui.new = TRUE;\n");
  fprintf(fh,"        UI_paint_client( &ui);\n");
  fprintf(fh,"        strcpy( oldfield, UI_item_search( &ui, fid, occ) );\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_OPTIONS:\n");
  fprintf(fh,"        %s_options( %s, fid);\n",modul,mod_l);
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_HELP:\n");
  fprintf(fh,"        ED_stream( \"%sM.HLP\", W_CENTER, W_CENTER, 10, 40, color_info);\n",modul);
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_GOTO:\n");
  fprintf(fh,"        if (%s_ctrl( %s, &ui, oldfid, oldfield) )\n",modul,mod_l);
  fprintf(fh,"          strcpy( oldfield, UI_item_search( &ui, fid, occ) );\n");
  fprintf(fh,"        else\n");
  fprintf(fh,"          fid = oldfid;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_NL:\n");
  fprintf(fh,"        KEYB_push( ARROW_START); /* Force repaint */\n");
  fprintf(fh,"      case  UI_CMD_DOWN:\n");
  fprintf(fh,"        if (%s_ctrl( %s, &ui, fid, oldfield) )\n",modul,mod_l);
  fprintf(fh,"          {\n");
  fprintf(fh,"          if ( (fid < %s_MAX_FID) )\n",modul);
  fprintf(fh,"            fid++;\n");
  fprintf(fh,"          else if (ui.new && fid == %s_MAX_FID)\n",modul);
  fprintf(fh,"            {\n");
  fprintf(fh,"            if (MSG_question( tx[tx_File]) && %s_put( %s, UI_CMD_INSERT) )\n",modul,mod_l);
  fprintf(fh,"              {\n");
  fprintf(fh,"              fid = UI_FID;\n");
  fprintf(fh,"              UI_init_items( &ui);\n");
  fprintf(fh,"              UI_paint_client( &ui);\n");
  fprintf(fh,"              UI_status_printf( &ui, tx[tx_updated]);\n");
  fprintf(fh,"              }\n");
  fprintf(fh,"            else\n");
  fprintf(fh,"              UI_status_printf( &ui, tx[tx_not_updated]);\n");
  fprintf(fh,"            }\n");
  fprintf(fh,"          strcpy( oldfield, UI_item_search( &ui, fid, occ) );\n");
  fprintf(fh,"          }\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_UP:\n");
  fprintf(fh,"        if (fid > UI_FID && %s_ctrl( %s, &ui, fid, oldfield) )\n",modul,mod_l);
  fprintf(fh,"          {\n");
  fprintf(fh,"          fid--;\n");
  fprintf(fh,"          strcpy( oldfield, UI_item_search( &ui, fid, occ) );\n");
  fprintf(fh,"          }\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_GET_PREV:\n");
  fprintf(fh,"      case  UI_CMD_GET_NEXT:\n");
  fprintf(fh,"      case  UI_CMD_GET_LAST:\n");
  fprintf(fh,"      case  UI_CMD_GET_FIRST:\n");
  fprintf(fh,"      case  UI_CMD_GET_EQ:\n");
  fprintf(fh,"      case  UI_CMD_GET_GE:\n");
  fprintf(fh,"      case  UI_CMD_GET_GT:\n");
  fprintf(fh,"      case  UI_CMD_GET_LE:\n");
  fprintf(fh,"      case  UI_CMD_GET_LT:\n");
  fprintf(fh,"      case  UI_CMD_SET_IDX:\n");
  fprintf(fh,"      case  UI_CMD_SET_PATTERN:\n");
  fprintf(fh,"        ui.new = FALSE;\n");
  fprintf(fh,"        if (%s_get( %s, cmd) )\n",modul,mod_l);
  fprintf(fh,"          {\n");
  fprintf(fh,"          UI_paint_client( &ui);\n");
  fprintf(fh,"          strcpy( oldfield, UI_item_search( &ui, fid, occ) );\n");
  fprintf(fh,"          }\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_INSERT:\n");
  fprintf(fh,"      case  UI_CMD_UPDATE:\n");
  fprintf(fh,"        if ( !%s_ctrl( %s, &ui, fid, oldfield) ) break;\n",modul,mod_l);
  fprintf(fh,"      case  UI_CMD_DELETE:\n");
  fprintf(fh,"        if (%s_put( %s, cmd) )\n",modul,mod_l);
  fprintf(fh,"          {\n");
  fprintf(fh,"          if (cmd != UI_CMD_INSERT)\n");
  fprintf(fh,"            {\n");
  fprintf(fh,"            fid = UI_FID;\n");
  fprintf(fh,"            UI_paint_client( &ui);\n");
  fprintf(fh,"            }\n");
  fprintf(fh,"          UI_status_printf( &ui, tx[tx_updated]);\n");
  fprintf(fh,"          }\n");
  fprintf(fh,"        else\n");
  fprintf(fh,"          UI_status_printf( &ui, tx[tx_not_updated]);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"       case  UI_CMD_TEXT:\n");
  fprintf(fh,"         VC_tx_modify( %s_tx, VC_DIM( %s_tx), %s_TX_FILE);\n",modul,modul,modul);
  fprintf(fh,"         UI_paint( &ui);\n");
  fprintf(fh,"         break;\n");
  fprintf(fh,"      default :\n");
  fprintf(fh,"        UI_edit_cmd( &ui, cmd);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  UI_end( &ui);\n");
  fprintf(fh,"  return (OK);\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_popup( %s *%s)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  UI ui;\n");
  fprintf(fh,"  short cmd, fid, occ, i, j, k, high_water_mark, max_cluster, len, fn;\n");
  fprintf(fh,"  BOOL goon, ret;\n");
  fprintf(fh,"  BYTE *cluster[%s_CLUSTER];\n",modul);
  fprintf(fh,"  BYTE head[BUFSIZ];\n");
  fprintf(fh,"  BYTE s[BUFSIZ];\n");
  fprintf(fh,"  for (len=i=0; i<%s_max_field; i++)\n",modul);
  fprintf(fh,"    len += (%s->len[i] + 1);\n",mod_l);
  fprintf(fh,"  for (i = 0, max_cluster = %s_CLUSTER; i < %s_CLUSTER; i++)\n",modul,modul);
  fprintf(fh,"    if ( (cluster[i] = (BYTE *)calloc( sizeof( BYTE), (len+1) ) ) == NULL )\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      max_cluster = i;\n");
  fprintf(fh,"      break;\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"  STR_set( head, \' \', len);\n");
  fprintf(fh,"  for (k=i=0; i<%s_max_field; i++)\n",modul);
  fprintf(fh,"    {\n");
  fprintf(fh,"    STR_paste( head, %s_tx[i], k, len);\n",modul);
  fprintf(fh,"    k += (%s->len[i] + 1);\n",mod_l);
  fprintf(fh,"    }\n");
  fprintf(fh,"  sprintf( s, \"%s\", tx[tx_popup], %s_tx[%s_max_field]);\n","%s  -  %s",modul,modul);
  fprintf(fh,"  if ( !UI_begin( &ui, s, W_CENTER, W_CENTER, max_cluster, len, UI_BUTTON_LEN, color_choise) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_mnubar_popup( &ui) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_button_pupup( &ui) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_acksel_popup( &ui) ) return (FAIL);\n");
  fprintf(fh,"  if ( !UI_ITEM_CLUSTER( &ui, (UI_FID), cluster, len, max_cluster, 2, 0, head, 1, 0) ) return (FAIL);\n");
  fprintf(fh,"  fn = UI_CMD_GET_FIRST;\n");
  fprintf(fh,"fetch_data:\n");
  fprintf(fh,"  UI_init_items( &ui);\n");
  fprintf(fh,"  for (i=0; i<max_cluster; i++)\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    if (!%s_get( %s, fn) )\n",modul,mod_l);
  fprintf(fh,"      break;\n");
  fprintf(fh,"    fn = UI_CMD_GET_NEXT;\n");
  fprintf(fh,"    STR_set( cluster[i], \' \', len);\n");
  fprintf(fh,"    for (k=j=0; j<%s_max_field; j++)\n",modul);
  fprintf(fh,"      {\n");
  fprintf(fh,"      STR_paste( cluster[i], %s->fp[j], k, len);\n",mod_l);
  fprintf(fh,"      k += (%s->len[j] + 1);\n",mod_l);
  fprintf(fh,"      }\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  high_water_mark = i;\n");
  fprintf(fh,"  UI_paint( &ui);\n");
  fprintf(fh,"  for (goon = TRUE, fid = UI_FID, occ = 0; goon; )\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    cmd = UI_cmd_get( &ui, &fid, &occ);\n");
  fprintf(fh,"    UI_status_printf( &ui, tx[tx_null]);\n");
  fprintf(fh,"    switch (cmd)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      case  UI_CMD_PAINT:\n");
  fprintf(fh,"        UI_paint_client( &ui);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_TOP:\n");
  fprintf(fh,"        occ = 0;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_BOT:\n");
  fprintf(fh,"        occ = high_water_mark - 1;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_PAGE_DOWN:\n");
  fprintf(fh,"        occ += ui.wcnrow;\n");
  fprintf(fh,"        if (occ > (high_water_mark-1) )\n");
  fprintf(fh,"          occ = (high_water_mark-1);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_DOWN:\n");
  fprintf(fh,"        if (occ < (high_water_mark-1) )\n");
  fprintf(fh,"          occ++;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_PAGE_UP:\n");
  fprintf(fh,"        occ -= ui.wcnrow;\n");
  fprintf(fh,"        if (occ < 0)\n");
  fprintf(fh,"          occ = 0;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_UP:\n");
  fprintf(fh,"        if (occ > 0)\n");
  fprintf(fh,"          occ--;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_HELP:\n");
  fprintf(fh,"        ED_stream( \"POPUP.HLP\", W_CENTER, W_CENTER, 10, 40, color_info);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_QUIT:\n");
  fprintf(fh,"        ret = goon = FALSE;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_GOTO:\n");
  fprintf(fh,"      case  UI_CMD_NL:\n");
  fprintf(fh,"        strncpy( %s->%s, cluster[occ], %s_LEN_%s);\n",mod_l,f[0].lname,modul,f[0].uname);
  fprintf(fh,"        %s->%s[%s_LEN_%s] = \'\\0\';\n",mod_l,f[0].lname,modul,f[0].uname);
  fprintf(fh,"        STR_trunc( %s->%s);\n",mod_l,f[0].lname);
  fprintf(fh,"        if ( (ret = CISAM_eq( &(%s->cisam), %s_%s, %s->%s) ) == OK)\n",mod_l,modul,f[0].lname,mod_l,f[0].lname);
  fprintf(fh,"          ret = VC_get_fields( %s->fp, &(%s->cisam), %s_max_field);\n",mod_l,mod_l,modul);
  fprintf(fh,"        goon = FALSE;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_NEW:\n");
  fprintf(fh,"        %s_maint( %s, (row+2), (col+2) );\n",modul,mod_l);
  fprintf(fh,"        fn = UI_CMD_GET_FIRST;\n");
  fprintf(fh,"        goto fetch_data;\n");
  fprintf(fh,"      case  UI_CMD_SET_PATTERN:\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_SET_IDX:\n");
  fprintf(fh,"        %s_get( %s, cmd);\n",modul,mod_l);
  fprintf(fh,"        fn = UI_CMD_GET_FIRST;\n");
  fprintf(fh,"        goto fetch_data;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_GET_FIRST:\n");
  fprintf(fh,"      case  UI_CMD_GET_EQ:\n");
  fprintf(fh,"      case  UI_CMD_GET_GE:\n");
  fprintf(fh,"      case  UI_CMD_GET_GT:\n");
  fprintf(fh,"      case  UI_CMD_GET_LE:\n");
  fprintf(fh,"      case  UI_CMD_GET_LT:\n");
  fprintf(fh,"        fn = cmd;\n");
  fprintf(fh,"        goto fetch_data;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      default :\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  for (i = 0; i < %s_CLUSTER; i++)\n",modul);
  fprintf(fh,"    free( cluster[i]);\n");
  fprintf(fh,"  UI_end( &ui);\n");
  fprintf(fh,"  return (ret);\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"BOOL %s_report( %s *%s)\n",modul,modul,mod_l);
  fprintf(fh,"  {\n");
  fprintf(fh,"  UI ui;\n");
  fprintf(fh,"  REP rep;\n");
  fprintf(fh,"  FILE *fh;\n");
  fprintf(fh,"  short cmd, fid, occ, i, k, len, ret, fn, field_check[%s_max_field];\n",modul);
  fprintf(fh,"  short page_len=72, page_wid=80, page_count, line_count;\n");
  fprintf(fh,"  BOOL goon;\n");
  fprintf(fh,"  BYTE trash[20],s[BUFSIZ];\n");
  fprintf(fh,"  extern BYTE *vc_dev[];\n");
  fprintf(fh,"  BYTE filename[FILENAME_LEN], dev[10], s_page_len[4], s_page_wid[4], s_dev[4];\n");
  fprintf(fh,"  time_t t;\n");
  fprintf(fh,"  struct tm *tm_p;\n");
  fprintf(fh,"  for (len=k=i=0; i<%s_max_field; i++)\n",modul);
  fprintf(fh,"    field_check[i] = ON;\n");
  fprintf(fh,"  strcpy( filename, \"%s.rep\");  strcpy( dev, vc_dev[0]);\n",mod_l);
  fprintf(fh,"  strcpy( s_page_len, \"47\");       strcpy( s_page_wid, \"80\");\n");
  fprintf(fh,"  sprintf( s, \"%s\", %s_tx[%s_max_field], tx[tx_report]);\n","%s  -  %s",modul,modul);
  fprintf(fh,"  if ( !UI_begin( &ui, s, W_CENTER, W_CENTER, 8, 30, UI_BUTTON_LEN, color_entry) ) return (FAIL);\n");
  fprintf(fh,"  if ( !UI_ITEM_FIELD( &ui, UI_FID,     filename,   31, 2, 15, tx[tx_filename], 2, 2) ) return (FAIL);\n");
  fprintf(fh,"  if ( !UI_ITEM_FIELD( &ui, (UI_FID+1), dev,         4, 3, 15, tx[tx_dev], 3, 2) ) return (FAIL);\n");
  fprintf(fh,"  if ( !UI_ITEM_FIELD( &ui, (UI_FID+2), s_page_len,  3, 4, 15, tx[tx_page_len], 4, 2) ) return (FAIL);\n");
  fprintf(fh,"  if ( !UI_ITEM_FIELD( &ui, (UI_FID+3), s_page_wid,  3, 5, 15, tx[tx_page_wid], 5, 2) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_mnubar_report( &ui) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_button_report( &ui) ) return (FAIL);\n");
  fprintf(fh,"  if ( !VC_default_acksel_report( &ui) ) return (FAIL);\n");
  fprintf(fh,"  UI_paint( &ui);\n");
  fprintf(fh,"  for (goon = TRUE, fid = UI_FID, occ = 0, fn = UI_CMD_GET_FIRST; goon; )\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    cmd = UI_cmd_get( &ui, &fid, &occ);\n");
  fprintf(fh,"    UI_status_printf( &ui, tx[tx_null]);\n");
  fprintf(fh,"    switch (cmd)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      case  UI_CMD_QUIT:\n");
  fprintf(fh,"        goon = FALSE;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_PAINT:\n");
  fprintf(fh,"        UI_paint_client( &ui);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_SET_IDX:\n");
  fprintf(fh,"        %s_get( %s, cmd);\n",modul,mod_l);
  fprintf(fh,"        fn = UI_CMD_GET_FIRST;\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_SELECT_FIELDS:\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  UI_CMD_GO:\n");
  fprintf(fh,"        UI_status_printf( &ui, tx[tx_processing]);\n");
  fprintf(fh,"        page_len = atoi( s_page_len);   page_wid = atoi( s_page_wid);\n");
  fprintf(fh,"        if (strcmp( dev, vc_dev[0]) == 0)  /* Disc */\n");
  fprintf(fh,"          REP_begin( &rep, filename, page_len, page_wid, 5, 3);\n");
  fprintf(fh,"        else\n");
  fprintf(fh,"          REP_begin( &rep, dev, page_len, page_wid, 5, 3);\n");
  fprintf(fh,"        REP_printf( &rep, REP_HEAD, 1, (page_wid/2 - strlen(s)/2), s);\n");
  fprintf(fh,"        t = time( &t);    tm_p = localtime( &t);\n");
  fprintf(fh,"        REP_printf( &rep, REP_HEAD, 1, 1, \"\%d.\%d.\%d\", tm_p->tm_mday, (tm_p->tm_mon+1), (1900+tm_p->tm_year) );\n");
  fprintf(fh,"        page_count = 1;\n");
  fprintf(fh,"        REP_printf( &rep, REP_HEAD, 1, (page_wid-10), \"%s\", tx[tx_page], page_count);\n","%s %d");
  fprintf(fh,"        REP_hline( &rep, REP_HEAD, 2, 1, (page_wid-1), \'-\');\n");
  fprintf(fh,"        REP_hline( &rep, REP_HEAD, 4, 1, (page_wid-1), \'-\');\n");
  fprintf(fh,"        REP_hline( &rep, REP_TAIL, 1, 1, (page_wid-1), \'-\');\n");
  fprintf(fh,"        for (i=0, col=1; i<%s_max_field; i++)\n",modul);
  fprintf(fh,"          if (field_check[i])\n");
  fprintf(fh,"            {\n");
  fprintf(fh,"            REP_printf( &rep, REP_HEAD, 3, col, %s_tx[i]);\n",modul);
  fprintf(fh,"            col += (%s->len[i] + 1);\n",mod_l);
  fprintf(fh,"            }\n");
  fprintf(fh,"        for (row=line_count=0; %s_get( %s, fn); )\n",modul,mod_l);
  fprintf(fh,"          {\n");
  fprintf(fh,"          line_count++;\n");
  fprintf(fh,"          fn = UI_CMD_GET_NEXT;\n");
  fprintf(fh,"          for (i=0,col=1; i<%s_max_field; i++)\n",modul);
  fprintf(fh,"            if (field_check[i])\n");
  fprintf(fh,"              {\n");
  fprintf(fh,"              REP_printf( &rep, REP_REPORT, row, col, %s->fp[i]);\n",mod_l);
  fprintf(fh,"              col += (%s->len[i] + 1);\n",mod_l);
  fprintf(fh,"              }\n");
  fprintf(fh,"          if (row < rep.report_len)\n");
  fprintf(fh,"            row++;\n");
  fprintf(fh,"          else\n");
  fprintf(fh,"            {\n");
  fprintf(fh,"            page_count++;\n");
  fprintf(fh,"            REP_printf( &rep, REP_HEAD, 1, (page_wid-10), \"%s\", tx[tx_page], page_count);\n","%s %d");
  fprintf(fh,"            row = 0;\n");
  fprintf(fh,"            REP_flush( &rep);\n");
  fprintf(fh,"            }\n");
  fprintf(fh,"          }\n");
  fprintf(fh,"        fn = UI_CMD_GET_FIRST;\n");
  fprintf(fh,"        REP_flush( &rep);\n");
  fprintf(fh,"        REP_end( &rep);\n");
  fprintf(fh,"        UI_status_printf( &ui, \"%s\", tx[tx_finished], tx[tx_pages], page_count, tx[tx_lines], line_count);\n","%s %d");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      default :\n");
  fprintf(fh,"        VC_default_cmd_report( cmd, &fid, &fn, filename, dev);\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  UI_end( &ui);\n");
  fprintf(fh,"  return (ret);\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"\n");
  fprintf(fh,"/** TESTCODE **\n");
  fprintf(fh,"#include <apl.h>\n");
  fprintf(fh,"main( )\n");
  fprintf(fh,"  {\n");
  fprintf(fh,"  short inull;\n");
  fprintf(fh,"  BOOL goon;\n");
  fprintf(fh,"  MNU mnu;\n");
  fprintf(fh,"  %s %s;\n",modul,mod_l);
  fprintf(fh,"  short i, c;\n");
  fprintf(fh,"  APL apl;\n");
  fprintf(fh,"  APL_begin( &apl, \" TEST  -  %s \");\n",modul);
  fprintf(fh,"  if ( !APL_mnu_new( &apl, \" %s \", 1, 0) ) return (FAIL);\n",modul);
  fprintf(fh,"  if ( !APL_mnu_new( &apl, \" Maintenance \", 11, 1) ) return (FAIL);\n");
  fprintf(fh,"  if ( !APL_mnu_new( &apl, \" Popup \", 12, 1) ) return (FAIL);\n");
  fprintf(fh,"  if ( !APL_mnu_new( &apl, \" Report\", 13, 1) ) return (FAIL);\n");
  fprintf(fh,"  if (!APL_mnu_default( &apl) )\n");
  fprintf(fh,"    MSG_err( \" Error ! \");\n");
  fprintf(fh,"  APL_paint( &apl);\n");
  fprintf(fh,"  MSG_msg( \"    Programmed by Einar Valen.  Copyright (c) 1991    \");\n");
  fprintf(fh,"  while ( (i = APL_mnu_pulldown( &apl) ) != APL_CMD_QUIT)\n");
  fprintf(fh,"    {\n");
  fprintf(fh,"    switch (i)\n");
  fprintf(fh,"      {\n");
  fprintf(fh,"      default :\n");
  fprintf(fh,"        APL_cmd_default( &apl, i); break;\n");
  fprintf(fh,"      case  11:\n");
  fprintf(fh,"        if ( !%s_begin( &%s) )\n",modul,mod_l);
  fprintf(fh,"          break;\n");
  fprintf(fh,"        %s_maint( &%s, 10, 10);\n",modul,mod_l);
  fprintf(fh,"        %s_end( &%s);\n",modul,mod_l);
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  12:\n");
  fprintf(fh,"        if ( !%s_begin( &%s) )\n",modul,mod_l);
  fprintf(fh,"          break;\n");
  fprintf(fh,"        if (%s_popup( &%s, 10, 10) )\n",modul,mod_l);
  fprintf(fh,"          MSG_msg( \"Selection made: %s !\", %s.%s);\n","%s",mod_l, f[0].lname);
  fprintf(fh,"        %s_end( &%s);\n",modul,mod_l);
  fprintf(fh,"        break;\n");
  fprintf(fh,"        else\n");
  fprintf(fh,"          MSG_msg( \"No selection made !\");\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      case  13:\n");
  fprintf(fh,"        if ( !%s_begin( &%s) )\n",modul,mod_l);
  fprintf(fh,"          break;\n");
  fprintf(fh,"        %s_report( &%s, 10, 10); break;\n",modul,mod_l);
  fprintf(fh,"        %s_end( &%s);\n",modul,mod_l);
  fprintf(fh,"        break;\n");
  fprintf(fh,"        else\n");
  fprintf(fh,"          MSG_msg( \"No selection made !\");\n");
  fprintf(fh,"        break;\n");
  fprintf(fh,"      }\n");
  fprintf(fh,"    }\n");
  fprintf(fh,"  APL_end( &apl);\n");
  fprintf(fh,"  }\n");
  fprintf(fh,"**/\n");
  fclose(fh);
  }
